---
  - name: Fix amavis ipv6
    ansible.builtin.lineinfile:
      path: /opt/zextras/conf/amavisd.conf.in
      insertafter: '# \$inet_socket_port = \[10024,10026\];.*'
      line: "$inet_socket_bind = '127.0.0.1';"
      regexp: \$inet_socket_bind.*
    when: inventory_hostname in groups["mtaServers"]
    tags:
      - amavis

    
     