---
  - name: Install Carbonio Application Server Ubuntu
    become: true
    apt: name={{ item }} state=present
    with_items:
      - "{{ appserver_packages }}"    
    when: ansible_os_family == "Debian" and inventory_hostname in groups["applicationServers"]
    tags:
      - install-carbonio-appserver
      
  - name: Install Carbonio Application Server RHEL
    yum: name={{ item }} state=present
    with_items:
      - "{{ appserver_packages }}"    
    when: (ansible_os_family == "RedHat" or ansible_os_family == "CentOS") and inventory_hostname in groups["applicationServers"]
    tags:
      - install-carbonio-appserver
