
# # External Ports
# - name: Allow MTA public ports
#   ansible.posix.firewalld:
#     port: "{{ item }}"
#     permanent: true
#     state: disabled
#   when: ansible_os_family == "RedHat" and inventory_hostname in groups["mtaServers"]
#   loop:
#     - 25/tcp
#     - 465/tcp
#     - 587/tcp

# - name: Allow Proxy ports
#   ansible.posix.firewalld:
#     port: "{{ item }}"
#     permanent: true
#     state: disabled
#   when: ansible_os_family == "RedHat" and inventory_hostname in groups["proxyServers"]
#   loop:
#     - 80/tcp
#     - 110/tcp
#     - 143/tcp
#     - 443/tcp
#     - 993/tcp
#     - 995/tcp
#     - 6071/tcp
#     - 8636/tcp
#     - 5222/tcp

# - name: Allow Videserver ports
#   ansible.posix.firewalld:
#     port: 20000-40000/tcp
#     permanent: true
#     state: disabled
#   when: ansible_os_family == "RedHat" and inventory_hostname in groups["videoServers"]

# # Internal ports

# - name: Allow Every node ports
#   ansible.posix.firewalld:
#     port: "{{ item }}"
#     permanent: true
#     state: disabled
#   when: ansible_os_family == "RedHat"
#   loop:
#     - 22/tcp
#     - 8301/udp
#     - 8301/tcp
#     - 9100/tcp
#     - 9256/tcp

# - name: Allow Postgres port
#   ansible.posix.firewalld:
#     port: "{{ item }}"
#     permanent: true
#     state: disabled
#   when: ansible_os_family == "RedHat" and inventory_hostname in groups["postgresServers"]
#   loop:
#     - 5432/tcp
#     - 9187/tcp

# - name: Allow Directory service port
#   ansible.posix.firewalld:
#     port: "{{ item }}"
#     permanent: true
#     state: disabled
#   when: ansible_os_family == "RedHat" and (inventory_hostname in groups["masterDirectoryServers"] or inventory_hostname in groups["replicaDirectoryServers"])
#   loop:
#     - 389/tcp
#     - 389/udp
#     - 636/tcp
#     - 9330/tcp

# - name: Allow MTA private port
#   ansible.posix.firewalld:
#     port: "{{ item }}"
#     permanent: true
#     state: disabled
#   when: ansible_os_family == "RedHat" and inventory_hostname in groups["mtaServers"]
#   loop:
#     - 25/tcp
#     - 465/tcp
#     - 587/tcp
#     - 7026/tcp

# - name: Allow AppServer private port
#   ansible.posix.firewalld:
#     port: "{{ item }}"
#     permanent: true
#     state: disabled
#   when: ansible_os_family == "RedHat" and inventory_hostname in groups["applicationServers"]
#   loop:
#     - 7025/tcp
#     - 7071/tcp
#     - 7072/tcp
#     - 7073/tcp
#     - 7110/tcp
#     - 7143/tcp
#     - 7993/tcp
#     - 7995/tcp
#     - 8080/tcp
#     - 8443/tcp
#     - 8735/tcp
#     - 8742/tcp
#     - 8743/tcp


# - name: Allow Videoserver private port
#   ansible.posix.firewalld:
#     port: "{{ item }}"
#     permanent: true
#     state: disabled
#   when: ansible_os_family == "RedHat" and inventory_hostname in groups["videoServers"]
#   loop:
#     - 8188/tcp
#     - 8090/tcp

# - name: Allow Proxy private port
#   ansible.posix.firewalld:
#     port: "{{ item }}"
#     permanent: true
#     state: disabled
#   when: ansible_os_family == "RedHat" and inventory_hostname in groups["proxyServers"]
#   loop:
#     - 9113/tcp
#     - 11211/tcp

# - name: Allow Consul server private port
#   ansible.posix.firewalld:
#     port: "{{ item }}"
#     permanent: true
#     state: disabled
#   when: ansible_os_family == "RedHat" and inventory_hostname in groups["serviceDiscoverServers"]
#   loop:
#     - 8300/tcp
#     - 9107/tcp
#     - 8302/tcp
#     - 8302/udp

#Disable firewalld
- name: Stop and disable firewalld.
  service:
    name: firewalld
    state: stopped
    enabled: False
  when: ansible_os_family == "RedHat"