---
# tasks file to prepare
   - name: Install dependencies Ubuntu
     become: true
     ansible.builtin.apt:
      pkg:
       - mc
       - libgmp10
       - libaio1
       - sysstat
       - fontconfig
       - dos2unix
       - ncdu
       - ccze
       - figlet
       - atop
       - bash-completion
       - nmon
       - telnet
       - curl
       - wget
       - netcat
       - tcpdump
       - sysstat
       - nmap
       - jq
       - net-tools
       - python3-psycopg2
     when: ansible_os_family == "Debian"
     tags:
        - set-os  
        
   - name: Install dependencies RHEL
     become: true
     ansible.builtin.yum:
      pkg:
       - mc
       - sysstat
       - fontconfig
       - dos2unix
       - bash-completion
       - open-vm-tools
       - telnet
       - curl
       - wget
       - nmap-ncat
       - tcpdump
       - sysstat
       - nmap
       - jq
       - net-tools
       - python3-psycopg2
     when: ansible_os_family == "RedHat"
     tags:
        - set-os 
       
   - name: Create alias for z
     become: true
     lineinfile:
      path: /root/.bashrc
      line: alias z='su - zextras'
     tags:
        - set-os 
   
   - name: Create alias for mc
     become: true
     lineinfile:
      path: /root/.bashrc
      line: alias mc='. /usr/share/mc/bin/mc-wrapper.sh'
     when: ansible_os_family == "Debian"    
     tags:
        - set-os 
